# Application Name
  # logging path
spring:
  application:
    name: kiosk
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/message?serverTimezone=UTC
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  security:
    user:
      name: admin
      password: 123456
server:
  port: 8080
logging:
  file:
    path: ./logs

neofaith:
  url: http://14.116.207.43:8062/services/


Hardware:
  scoketPort: 8899
  ip1: 127.0.0.1
  ip2: 127.0.0.1
  ip3: 127.0.0.1



app-pay:
  mid: 1234567
  tid1: 123131
  tid2: 123131
  tid3: 56567567
  ip: 127.0.0.1
  port: 8080
